### ISSUE TITLE
maintain architecture

### ISSUE THREAD

**Issue by andreigec** [philpep/imago#11]
Is there any way to ensure that imago maintains the current architecture when looking for the newest docker image? When upgrading a container that has a multiarch image, it seems to always choose the first (amd64), which causes my raspberry pi (arm) to fail.

**Comment by philpep** [comment]
I think I can understand how to get correct digest for a given architecture when looking at the registry. However I cannot see how to get current architecture used in kubernetes manifest, do you have a field for this in kubernetes manifests ?

**Comment by philpep** [comment]
Hi @andreigec , I just pushed a change in 60c8cb5ca21266d3bf3d3dfbfef58864bc7e596e which might fixes your issue (using github.com/containers/image for registry operations). Can you tell me if this fixes or not your issue ?
