### ISSUE TITLE
go get not working?

### ISSUE THREAD

**Issue by cyj5230** [philpep/imago#14]
I am using imago in my Jenkins pipeline, and run imago in command line:
```
go get github.com/philpep/imago/...
$(go env GOPATH)/bin/imago -n default -check-pods -update
```
This works perfectly in these months, but since today, it is stuck in the go get command. 
Would you mind checking is there anything wrong?

**Comment by philpep** [comment]
Hi, what error do you get ? I cannot reproduce this issue.

**Comment by cyj5230** [comment]
I cannot reproduce either... I will close the issue then, thank you very much
