### ISSUE TITLE
Automatic rebuilt of imago if dependent docker images are rebuilt

### ISSUE THREAD

**Issue by kmindi** [philpep/imago#17]
In Docker Hub it is possible to enable an automatic build trigger that is triggered when a dependent repository is updated. This ensures the imago docker container is also up to date automatically instead of only manually when something new is added.

**Comment by philpep** [comment]
Hi, @kmindi , I checked this under "repository links -> enable for base image". But seems link between my github account and docker hub was somehow broken. Let see if that fixes the issue.
