### ISSUE TITLE
Unable to use --restart inside kubernetes cluster

### ISSUE THREAD

**Issue by pokoli** [philpep/imago#23]
Hi, 

First of all thank you so much for creating such tool. This makes our live easier!

I'm trying to run it on inside a 1.20 k8s cluster using the defautl configuration explained in the readme.
If I use the "--update" flag everything seems to work well:

```
$ kubectl create job --from=cronjob/imago update-test
$ kubectl logs -f job/update-test                                                                                                                                                                  
2021/01/29 15:56:19 checking test/Deployment/postgres
2021/01/29 15:56:21     postgres ok
2021/01/29 15:56:22 checking test/CronJob/imago
2021/01/29 15:56:23     imago ok
```

but if I change the "--update" flag to "--restart" I get the following output:

```
$ kubectl create job --from=cronjob/imago update-test
$  kubectl logs -f job/update-test -
2021/01/29 15:57:16 checking test-trytonacademy/Deployment/postgres
2021/01/29 15:57:16 replicasets.apps "postgres-67c4854f74" is forbidden: User "system:serviceaccount:test:imago" cannot get resource "replicasets" in API group "apps" in the namespace "test"
2021/01/29 15:57:19 checking test-trytonacademy/CronJob/imago
```

It seems an issue related to permission but I'm unable to fix it. Do you have any clue? Or it is really a bug? 
If this is something due to configuration I will be happy to update the documentationt to fix it. 

TIA

**Comment by philpep** [comment]
Hi, if you run in cluster you probably have deployed the ClusterRole defined in https://github.com/philpep/imago/blob/master/deploy/serviceaccount.yaml

I didn't tested it with `-restart` so probably the issue come from there. Probably you need to add `replicasets` in the list here https://github.com/philpep/imago/blob/master/deploy/serviceaccount.yaml#L37
